version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate appointments && python manage.py runserver 0.0.0.0:8000"
    container_name: code
    volumes:
      - .:/code
      - db.sqlite3
    ports:
      - "8000:8000"