# Generated by Django 3.1.5 on 2021-01-28 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_user_is_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='date',
            field=models.DateField(default=datetime.date),
        ),
    ]
